version: '3.8'
services:
  database:
    container_name: database-container
    networks:
      - connect-database
    build:
      context: .
      dockerfile: ./Dockerfile
      target: database
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    networks:
      - connect-database
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

networks:
  connect-database:
    driver: bridge


